version: '3.9'

services:

   db:
        image: mysql:5.7
        env_file: .env  
        environment:
          MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
          MYSQL_DATABASE: $MYSQL_DBNAME
          MYSQL_USER: $MYSQL_USER
          MYSQL_PASSWORD: $MYSQL_PASSWORD
        ports:
          - "3306:3306"
        volumes:
          - ./data/db:/var/lib/mysql
               
volumes:
    data:

