version: '3.9'

services:

   web:
        image: nginx:1.19
        restart: always
        ports:
          - 80:80
        volumes:
          - ./config/nginx-templates:/etc/nginx/templates
          - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
          - ./files/intranet:/var/www/html
          - ./logs/nginx:/var/log/nginx
               
volumes:
    config:
    files:  
    logs:
